DROP DATABASE IF EXISTS CHATAPP;
CREATE DATABASE CHATAPP;

USE CHATAPP;

CREATE TABLE USERNAMES (
  USERNAME VARCHAR(40) PRIMARY KEY, 
  NAME VARCHAR(40),
  SURNAMES VARCHAR(40),
  PASSWORD VARCHAR(255),
  IMAGE VARCHAR(255)
);

CREATE TABLE MESSAGES (
  ID VARCHAR(100) PRIMARY KEY,
  TEXT VARCHAR(255),
  FROMUSER VARCHAR(100),
  TOUSER VARCHAR(100)
);